syntax = "proto3";

import "google/protobuf/empty.proto";

package computenode;

service ComputeNode { 
    // Create a new index, intialized with random vectors, based on the specified parameter
    rpc CreateNewIndex (NewIndexRequest) returns (IndexCreationReply) { }

    // Load an existing index from the specified path (disk, S3, etc...) 
    rpc LoadExistingIndex (ExistingIndexRequest) returns (IndexCreationReply) { }

    // Perform search over an existing index
    rpc SearchIndex (SearchIndexRequest) returns (SearchIndexReply) { }

    // Heartbeat endpoint that can be used to check if the server is alive
    rpc Heartbeat (HeartbeatRequest) returns (HeartbeatReply) { }

    // RPC to print and reset the collected system metrics
    rpc PrintAndResetMetrics (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

// Messages used to create new/load existing index
message NewIndexRequest { 
    int32 vector_dimension = 1;
    int32 num_vectors = 2;
    int32 num_clusters = 3; 
    bool store_index_locally = 4;
    int32 num_search_workers = 5;
}

message ExistingIndexRequest { 
    string index_uri = 1; 
    bool store_index_locally = 2;
    bool store_index_on_disk = 3;
    int32 num_search_workers = 4;
}

message IndexCreationReply { 
    int32 index_id = 1;
}

// Messages to search an existing index
message SearchIndexRequest { 
    int32 index_id = 1;
    int32 top_k = 2;
    int32 num_probe = 3;
    float recall_target = 4;
    repeated float search_vectors = 5;
}

message SearchIndexReply { 
    repeated float result_distances = 1;
    repeated int64 result_ids = 2;
}

// Heartbeat Data
message HeartbeatRequest { 
    bool value_to_return = 1;
}

message HeartbeatReply { 
    bool reply_value = 1;
}