name: quake-env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pytorch-cpu
  - faiss-cpu
  - grpc-cpp
  - matplotlib
  - arrow-cpp
  - compilers
  - pytest
  - pip
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-mermaid
    - graphviz
    - pyyaml